name: Deploy to EC2

on:
  push:
    branches:
      - main   # yoki master — sizning asosiy branch nomingiz

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodingiz
      uses: actions/checkout@v3

    - name: EC2 serverga ulanish va deploy qilish
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          ls -la
          cd /home/ubuntu/mini-twitter-backend
          git pull origin main
          npm install
          npm run build
