name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}          # EC2 public IP yoki DNS
        username: ${{ secrets.EC2_USER }}      # Masalan, ec2-user yoki ubuntu
        key: ${{ secrets.EC2_KEY }}            # Private SSH key (to‘liq)
        port: 22
        script: |
          echo "Deploy started"
          cd /home/ec2-user/myapp                # O‘zingizning yo‘lingizga moslashtiring
          git pull origin main                    # Kodingizni yangilash (agar git bilan ishlasangiz)
          ./deploy.sh                            # Sizning deploy skriptingiz yoki buyruqlar
          echo "Deploy finished"
